# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: target.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctarget.proto\"\xb3\x01\n\x06Target\x12\x1c\n\x05shape\x18\x01 \x02(\x0e\x32\r.Target.Shape\x12\x1c\n\x05\x63olor\x18\x02 \x02(\x0e\x32\r.Target.Color\":\n\x05Shape\x12\n\n\x06SQUARE\x10\x00\x12\n\n\x06\x43IRCLE\x10\x01\x12\x0c\n\x08TRIANGLE\x10\x02\x12\x0b\n\x07OCTAGON\x10\x03\"1\n\x05\x43olor\x12\x07\n\x03RED\x10\x00\x12\n\n\x06YELLOW\x10\x01\x12\x08\n\x04\x42LUE\x10\x02\x12\t\n\x05GREEN\x10\x03')



_TARGET = DESCRIPTOR.message_types_by_name['Target']
_TARGET_SHAPE = _TARGET.enum_types_by_name['Shape']
_TARGET_COLOR = _TARGET.enum_types_by_name['Color']
Target = _reflection.GeneratedProtocolMessageType('Target', (_message.Message,), {
  'DESCRIPTOR' : _TARGET,
  '__module__' : 'target_pb2'
  # @@protoc_insertion_point(class_scope:Target)
  })
_sym_db.RegisterMessage(Target)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TARGET._serialized_start=17
  _TARGET._serialized_end=196
  _TARGET_SHAPE._serialized_start=87
  _TARGET_SHAPE._serialized_end=145
  _TARGET_COLOR._serialized_start=147
  _TARGET_COLOR._serialized_end=196
# @@protoc_insertion_point(module_scope)
